### PR TITLE
non zero exit in case of lint fails or errors

### LINKED ISSUE #75: Report error in case of module lint fails
Now, when we run a `yarn run-tool` on a project, even when there're fails or even error, it is been resolved instead of throwing.
Output in console now.

We would like to throw an error.

### PR DESCRIPTION
**Pull request by kanthesha**
we need the tool to exit with a non-zero exit code if there are any lint errors or if the tool throws an error for any reason. This way, when running the tool in a GitHub workflow, the job will fail.

* Fixes #75

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -71,13 +71,18 @@ export async function main({
     outputLogger,
   });
 
-  await lintProjects({
+  const isAllPassed = await lintProjects({
```
Comment (mcmire) [inline src/main.ts:74]: Nit: What do you think about calling this `isAllSuccessful` instead of `isAllPassed`, since `isAllPassed` in `src/report-project-lint-result.ts` strictly means that there were no failing rules, but in this case it means not only that, but also no errors were thrown?

**Review by mcmire — APPROVED** [review]
Had a small suggestion, but looks good regardless.
